project_id = "tdbsvchatbreibzludaf"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.process-document]
verify_jwt = false

[functions.chat-with-document]
verify_jwt = false